# Generated by Django 5.1.1 on 2024-09-10 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='nazev',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='rok',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='zanr',
        ),
        migrations.RemoveField(
            model_name='member',
            name='joined_date',
        ),
    ]
